lightning_seed: 42
model:
    name: PIBTransformer
    d_model: 20
    nhead: 4
    num_layers: 5
    dim_feedforward: 50
    dropout: 0.1
    ignore_initial: 99
    ema_decay: 0.999
    optimizer: Adam
    lr: 0.001
    train_seq_len: 1000
train:
    max_epochs: 3
    root_dir: ./results/transformer
data:
    data_path: ./data/icassp-person-in-bed-track-1/train.json
    train_validate_test_split: [14, 3, 3]
    train_batch_size: 128
    validate_batch_size: 64